# config
export XDG_CONFIG_HOME=$HOME/.config

#homebrew
export HOMEBREW_BIN=/opt/homebrew/bin

# batconfig
export BAT_CONFIG_PATH="$HOME/.dotfiles/bat/bat.conf"

# tealdeer
export TEALDEER_CONFIG_DIR=$XDG_CONFIG_HOME/tealdeer

# autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#9399b2"

# scripts
export SCRIPTS=$HOME/scripts

# llvm
export LLVM_BIN=/opt/homebrew/opt/llvm/bin
export LDFLAGS=$LDFLAGS:"-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS=$CPPFLAGS:"-I/opt/homebrew/opt/llvm/include"

# golang
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
# export PATH=$PATH:$GOBIN
# export GOPROXY=goproxy.cn

# java
# export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.4.jdk/Contents/Home
# export PATH=$PATH:$JAVA_HOME

# rust
export RUSTUP_HOME=$HOME/rust/.rustup
export CARGO_HOME=$HOME/rust/.cargo
export CARGO_BIN=$CARGO_HOME/bin

# editor
export EDITOR='nvim'

# mason for neovim
export MASON_BIN=$HOME/.local/share/nvim/mason/bin

# pyenv
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

export PATH=$PATH:$HOMEBREW_BIN:$SCRIPTS:$LLVM_BIN:$GOBIN:$JAVA_HOME:$CARGO_BIN:$MASON_BIN
