# env
source ~/.dotfiles/zsh/env.zsh

# alias
source ~/.dotfiles/zsh/aliases.zsh

# functions
source ~/.dotfiles/zsh/functions.zsh

# plugin for zsh
source ~/.dotfiles/zsh/plugins.zsh

# starship
eval "$(starship init zsh)"

# zoxide
eval "$(zoxide init zsh --cmd j)"

# fzf
source ~/.dotfiles/zsh/fzf.zsh

# conda
__conda_setup="$('/opt/homebrew/Caskroom/miniforge/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
    . "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
  else
    export PATH="/opt/homebrew/Caskroom/miniforge/base/bin:$PATH"
  fi
fi
unset __conda_setup

# Github token for homebrew
export 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
