# alias
source ~/.dotfiles/zsh/aliases.zsh

# functions
source ~/.dotfiles/zsh/functions.zsh

# plugin for zsh
source ~/.dotfiles/zsh/plugins.zsh

# starship
eval "$(starship init zsh)"

# zoxide
eval "$(zoxide init zsh --cmd j)"

# fzf
source ~/.dotfiles/zsh/fzf.zsh

